### ISSUE TITLE
Colored signs don't work on servers.

### ISSUE THREAD

**Issue by Claycorp** [GoryMoon/MoarSigns#13]
http://i.imgur.com/5R9JNyG.png

Nothing more than Orange text that is rather large on a "Big oak sign" (It should be Dark oak sign instead)

V1.1.1

**Comment by GoryMoon** [comment]
About the text colors not working I think I have fixed, not sure what it was as I don't have the problem on a dedicated server. I think it could be that the character escaping I had turned to different character on different computers, now I set the chars as  escaped numbers as that's what minecraft also is checking for when applying the effects.

Regarding the shadows, the shadows are the standard ones that's in the FontRenderer, the thought behind the shadow was that the user could add shadows where they wanted and looked good and some of the colors was obviously not going to work.

**Comment by Claycorp** [comment]
Awsome. I'll test it ASAP.

Yeah after I messed with it for a while i remembered that the shadows of the two always conflicted. Thanks for the options though! Definitely liking the new system much more. :+1:

**Comment by Claycorp** [comment]
Sorry for such a late reply been quite busy.
It still doesn't work.
http://i.imgur.com/At9gFr9.png

**Comment by GoryMoon** [comment]
Hm... I have no clue to why it's like that. Looks it has something to do with the § letter somehow. I might have to make my own version of the Fontrenderer or something. I will look into it.

**Comment by GoryMoon** [comment]
Is this an issue any more?

**Comment by Claycorp** [comment]
Colors seem to work fine. Though when editing signs color/format codes seem to be dropped.
IE: Make sign, Color text, Done. Edit sign, Add Formatting, Done = No format only color.
Make sign, Format, Color, Done. Edit sign is missing color but not format and saving saves it like this.

If you need pictures let me know.

**Comment by Claycorp** [comment]
Ok Quark is to blame for the right click editing of signs. I would highly recommend putting in a warning about this as it can delete formatting and will mess up the sign tool.
I will post an issue on Quark also.
